version: '3.8'
services:
  jetstream:
    build: .
    init: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      ENVIRONMENT: production
      JETSTREAM_POSTGRES_DBURI: postgres://postgres:postgres@postgres:5432/postgres
      JETSTREAM_SESSION_SECRET: '${JETSTREAM_SESSION_SECRET}'
      JETSTREAM_CLIENT_URL: http://localhost:3333/app
      JETSTREAM_SERVER_DOMAIN: localhost:3333
      JETSTREAM_SERVER_URL: http://localhost:3333
      EXAMPLE_USER_OVERRIDE: 'true'
      AUTH0_DOMAIN: '${AUTH0_DOMAIN}'
      AUTH0_M2M_DOMAIN: '${AUTH0_M2M_DOMAIN}'
      AUTH0_CLIENT_ID: '${AUTH0_CLIENT_ID}'
      AUTH0_MGMT_CLIENT_ID: '${AUTH0_MGMT_CLIENT_ID}'
      AUTH0_MGMT_CLIENT_SECRET: '${AUTH0_MGMT_CLIENT_SECRET}'
      AUTH0_CLIENT_SECRET: '${AUTH0_CLIENT_SECRET}'
      SFDC_API_VERSION: '${SFDC_API_VERSION}'
      SFDC_CONSUMER_SECRET: '${SFDC_CONSUMER_SECRET}'
      SFDC_CONSUMER_KEY: '${SFDC_CONSUMER_KEY}'
      SFDC_CALLBACK_URL: '${SFDC_CALLBACK_URL}'
      NX_ROLLBAR_KEY: '${NX_ROLLBAR_KEY}'
      NX_AMPLITUDE_KEY: '${NX_AMPLITUDE_KEY}'
      NX_AUTH_AUDIENCE: '${NX_AUTH_AUDIENCE}'
    ports:
      - '3333:3333'
    links:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - '5555:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      # this command checks if the database is ready directly on the source db server
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5
  db_seed:
    build:
      context: .
      dockerfile: ./Dockerfile.db-migration
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      ENVIRONMENT: production
      JETSTREAM_POSTGRES_DBURI: postgres://postgres:postgres@postgres:5432/postgres

volumes:
  db:
    driver: local
